### ISSUE TITLE
Separate the clarified filename with color

### ISSUE THREAD

**Issue by quantizor** [tschaub/karma-source-map-support#2]
This plugin is super useful, thank you!

Could we take it a step further and set the the added output to a different color (maybe yellow?) so it's easier to distinguish in the wall of text that is emitted?

For some reason, my results are definitely more verbose than the example in the readme.

```
    TypeError: 'undefined' is not an object (evaluating 'this.items.map')
        at renderContent (/var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:73:0 <- /Users/esj/code/uikit/UIList/index.jsx:37:8)
        at render (/var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:63:0 <- null:0:0)
        at /var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:7957:0 <- node_modules/react/lib/ReactCompositeComponent.js:789:0
        at /var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:7984:0 <- node_modules/react/lib/ReactCompositeComponent.js:816:0
        at ReactCompositeComponent__renderValidatedComponent (/var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:14533:0 <- node_modules/react/lib/ReactPerf.js:70:0)
        at /var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:7405:0 <- node_modules/react/lib/ReactCompositeComponent.js:237:0
        at ReactCompositeComponent_mountComponent (/var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:14533:0 <- node_modules/react/lib/ReactPerf.js:70:0)
        at /var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:15350:0 <- node_modules/react/lib/ReactReconciler.js:38:0
        at mountComponentIntoNode (/var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:13136:0 <- node_modules/react/lib/ReactMount.js:249:0)
        at /var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:19043:0 <- node_modules/react/lib/Transaction.js:134:0
        at batchedMountComponentIntoNode (/var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:13163:0 <- node_modules/react/lib/ReactMount.js:276:0)
        at /var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:19043:0 <- node_modules/react/lib/Transaction.js:134:0
        at /var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:10204:0 <- node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:0
        at batchedUpdates (/var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:17211:0 <- node_modules/react/lib/ReactUpdates.js:110:0)
        at /var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:13296:0 <- node_modules/react/lib/ReactMount.js:409:0
        at ReactMount__renderNewRootComponent (/var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:14533:0 <- node_modules/react/lib/ReactPerf.js:70:0)
        at /var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:13383:0 <- node_modules/react/lib/ReactMount.js:496:0
        at React_render (/var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:14533:0 <- node_modules/react/lib/ReactPerf.js:70:0)
        at /var/folders/2l/n403lxtd3j32_3jtgypbwpr80000gn/T/51a10ff2544d514c05b2eb7ee980a77b.browserify:235:0 <- /Users/esj/code/uikit/UIList/unit.jsx:80:12
```

**Comment by alexbuijs** [comment]
+1

**Comment by csulok** [comment]
+1
